language: go
install: true

branches:
  only:
    - "master"

go:
  - "1.9"
  - "1.10.x"
  - "master"

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - go: master

before_install:
  - curl https://glide.sh/get | sh
  - glide install

script:
  - ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
