language: go
install: true
go:
  - "1.9"
  - "1.10.x"

before_install:
  - curl https://glide.sh/get | sh
  - glide install
  - sudo apt-get update && sudo apt-get install -y iputils-ping

script:
  - ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
