language: go
install: true

branches:
  only:
    - "master"

env:
  - GO111MODULE=on

go:
  - "1.11.x"
  - "1.12.x"
  - "master"

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - go: master

before_install:
  - go mod download
  - go mod vendor

script:
  - ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
