success_rate_threshold: 0.74
success_time_threshold: 1s
single_check_timeout: 10s
minimal_checking_period: 15s
maximal_checking_period: 60s
persister:
  dynamodb:
    enabled: false
    region: eu-west-1
    table_name: pingor
    device_name: pc1
http:
  urls:
    - https://www.google.com
    - https://www.facebook.com
    - https://www.twitter.com
dns:
  hosts:
    - google.com
    - facebook.com
    - twitter.com
    - github.com
metrics:
  enabled: false
  port: 9111
