success_rate_threshold: 0.74
success_time_threshold: 1s
single_check_timeout: 10s
minimal_checking_period: 30s
maximal_checking_period: 60s
http:
  urls:
    - https://wp.pl
    - https://www.onet.pl
    - https://www.google.com
    - https://www.upc.pl
dns:
  hosts:
    - wp.pl
    - onet.pl
    - google.com
    - upc.pl
    - mbank.pl
ping:
  ips:
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 1.1.1.1
